spring.application.name=sca
server.port=${PORT:8000}
spring.profiles.active=local
server.error.include-stacktrace=never

spring.datasource.url=jdbc:${DB_DRIVER:mysql}://${DB_HOST:localhost}:${DB_PORT}/${DB_NAME}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.type.preferred_uuid_jdbc_type=CHAR

api.security.token.secret=${JWT_SECRET}
api.security.cors.origins=${CORS_ORIGINS}
api.security.cookie.secure=${COOKIE_SECURE:false}
api.security.cookie.samesite=${COOKIE_SAMESITE:Strict}

springdoc.swagger-ui.enabled=false